### ISSUE TITLE
Prompts to install .Net

### ISSUE THREAD

**Issue by Craig-Humphrey** [SpoinkyNL/RGB.NET-Layout-Editor#4]
Whenever I try to run LayoutEditor.UI.exe from your v1.9 zip, it prompts me to install .Net:
![image](https://user-images.githubusercontent.com/54136774/185844800-02bc8380-271c-4a6e-9a60-4be4a54b8646.png)
Clicking Yes or No has no effect.

However I already have .Net installed (framework: v4.5.x, v4.6.x, v4.7.x, v4.8.x and runtime: v6.0).

I see from the LayoutEditor.UI.dll.config that it's looking for .Net 4.6, though editing it to 4.7 has no effect.

Any ideas?

**Comment by helderbarboza** [comment]
Installing ".NET Desktop Runtime 5.0.17" solved for me:
https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by Craig-Humphrey** [comment]
Thanks! Worked for me too.
